username = input('Введите ваше имя: ')
title = input('Введите заголовок заметки: ')
content = input('Введите описание заметки: ')
status = input('Введите статус заметки:  ')
created_date = input('Введите дату создания (дд:мм:гггг): ')
issue_date = input('Введите дату оканчания заметки (дд:мм:гггг): ')

title1 = input('Введите название заголовка: ')
title2 = input('Введите название заголовка: ')
title3 = input('Введите название заголовка: ')
all_title = [title1, title2, title3]
print('Имя пользователя:', username)
print('Заголовок заметки:',title)
print('Описание заметки:',content)
print('Статус заметки:',status)
print('Дата создания заметки:',created_date)
print('Дата истечения aзаметки:',issue_date)
print(all_title)